Updated to work with NXRM 3.30.0-01
sonatype-nexus-community/nexus-repository-apk pull request #34
Opened 2021-03-31 12:03 UTC by mikeq

Updated to work with NXRM 3.30.0-01

This pull request makes the following changes:
* Update version numbers in the pom files

I am not a Java developer so I have made the changes I thought were required to make the plugin work with NXRM 3.30.0-01 and tested it works with that version of NXRM. If there is something else that needs to be done just let me know.

* Fixes #33 

cc @DarthHater @bhamail

2021-03-31 16:18 UTC, joedragons commented
Looks fine to me tho not sure if the change to -19 is needed or done by another process.  Defer to others you CCed.  Thanks for the contribution.

2021-04-01 21:25 UTC, bhamail requested changes
Looks good! Please revert the version bump as noted in my comments.
I'm also looking into why the CI build didn't appear to run (unrelated to your changes).

2021-04-01 21:25 UTC, bhamail commented on nexus-repository-apk-it/pom.xml
> +    <version>0.0.19-SNAPSHOT</version>
You should be able to revert this change, and the "maven release" process takes care of releasing version `0.0.18` and incrementing the development version to the next revision (`0.0.19-SNAPSHOT`).

2021-04-01 21:25 UTC, bhamail commented on nexus-repository-apk/pom.xml
> +    <version>0.0.19-SNAPSHOT</version>
see prior comment. can just revert this change.

2021-04-01 21:25 UTC, bhamail commented on pom.xml
> +  <version>0.0.19-SNAPSHOT</version>
see prior comment. can just revert this change.

2021-04-01 21:37 UTC, bhamail commented
One more minor request: Could you update the README.md file, adding to the `Plugin Version` table:

| v0.0.12        | 3.28.0-01                |

becomes:

| v0.0.12        | 3.28.0-01                |
| v0.0.18        | 3.30.0-01                |

2021-04-06 15:44 UTC, bhamail commented
Thanks @mikeq ! Merging now. (Still now certain why the CI didn't fire, but I verified it works with a local CI build).

2021-04-06 15:44 UTC, merged